kind: Service
apiVersion: v1
metadata:
  name: kcrwebservice
  labels:
    app: kcrwebservice
spec:
  selector:
    run: kcrwebservice
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kcrwebservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: kcrwebservice
        app: kcrwebservice
    spec:
      containers:
      - name: kcrwebservice
        image: kmamlv2preview7614009659.azurecr.io/kcrwebservice:#{BUILDID}#
        imagePullPolicy: Always
        env:
        - name: HOST_PLATFORM
          value: "ACS Kubernetes"
        ports:
          - containerPort: 8000
      imagePullSecrets:
      - name: regsecret