kind: Service
apiVersion: v1
metadata:
  name: #{service-name}#
  labels:
    app: #{service-name}#
spec:
  selector:
    run: #{service-name}#
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: #{service-name}#
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: #{service-name}#
        app: #{service-name}#
    spec:
      containers:
      - name: kcrwebservice
        image: #{acr-name}#/#{service-name}#:#{BUILDID}#
        imagePullPolicy: Always
        env:
        - name: HOST_PLATFORM
          value: "ACS Kubernetes"
        ports:
          - containerPort: 8000
      imagePullSecrets:
      - name: regsecret